version: '3.8'

services:

  # client:
  #   container_name: client
  #   restart: always
  #   build: ./client
  #   depends_on:
  #     - server
  #   ports:
  #     - 9000:90

  server:
    container_name: api_server
    restart: always
    build: ./server
    depends_on:
      - database
    volumes:
      - ./server/src/:/server/src
    ports:
      - "80:80"
  
  database:
    container_name: mongo_database
    image: mongo:6.0
    restart: always
    volumes:
      - serverDB:/data/db
    ports:
      - "27017:27017"
    expose:
      - "27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  # database_interface:
  #   container_name: mongo_interface
  #   image: mongo-express:1.0.0-alpha
  #   restart: always
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINUSERPASSWORD: root
  #     ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/      

volumes:
  serverDB: